DELETE  HTTP/1.1 http://localhost:8080/oders/ HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhcmEuYWRtaUB2ZWdnaWUuY29tIiwiaWF0IjoxNjg5MzQxNzU4LCJleHAiOjE2ODkzNDUzNTgsInN1YiI6IjYifQ.5VaogCP9eQXMn6gwaaQN02b2bBfu6I7JLcGNxWeYE9s

{
  "name": "Paola Perez",
  "email": "paola.admi@veggie.com",
  "password": "123456",
  "role": "admin"
}