POST  http://localhost:8080/users HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhb2xhLmFkbWlAdmVnZ2llLmNvbSIsImlhdCI6MTY4OTM1MTQwNywiZXhwIjoxNjg5MzU1MDA3LCJzdWIiOiI3In0.lw0H2vBG44ch6fU6D3_HWglvLPsKgipst9JuzEDI8Cs

{
  "name": "Paola Martinez",
  "email": "paola.admi@veggie.com",
  "password": "123456",
  "role": "admin"
}