DELETE  http://localhost:8080/users/0 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJlbWFpbCI6Im1lc2Vyb0B2ZWdnaWUuY29tIiwiaWF0IjoxNjg5MDA1NTE5LCJleHAiOjE2ODkwMDkxMTksInN1YiI6IjUifQ.jMMFcFLq1fnwipN7y09oxFh5cDeSbeBcSBZ0jOybKS0