POST  http://localhost:8080/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lc2Vyb0B2ZWdnaWUuY29tIiwiaWF0IjoxNjg4MTY3ODY2LCJleHAiOjE2ODgxNzE0NjYsInN1YiI6IjUifQ.vt1uz8l-dWgx8Gcxqr1kBlgSn1ja5b6cNqougFiJddc

{
  "name": "Agua 750ml",
  "price": 7,
  "image": "src/assets/agua750.jpg",
  "type": "Almuerzo"
}