
const bearerToken = {
    token:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5MTUwMzc0NywiZXhwIjoxNjkxNTA3MzQ3LCJzdWIiOiIyIn0.Lfj7OzvSAUnj_qpxZaW8ka7ijN4mbMTz3Fb0I8kOYhw"
}

export default bearerToken