
const bearerToken = {
    token:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5MTUwNzc4NCwiZXhwIjoxNjkxNTExMzg0LCJzdWIiOiIyIn0.zjV12Yt-Ww9zA2dIhj2ZzxAzKZ8abcVgNxflsabmYLk"
}

export default bearerToken